### PR TITLE
Fix Windows support

### LINKED ISSUE #36: Fix Windows support
From the PR at https://github.com/netlify/netlify-plugin-edge-handlers/pull/33, it appears that there might be some issues when running this plugin on Windows (apparently due to file path delimiters difference). Specifically the CI tests [fail on Windows](https://github.com/netlify/netlify-plugin-edge-handlers/pull/33/checks?check_run_id=1102569449).

```
┌─────────────────────────────┐
│        Netlify Build        │
└─────────────────────────────┘

> Version
  @netlify/build 3.3.5

> Flags
  cwd: 'D:\a\netlify-plugin-handler\netlify-plugin-handler\test/../integration-test'

> Current directory
  D:\a\netlify-plugin-handler\netlify-plugin-handler\integration-test

> Config file
  D:\a\netlify-plugin-handler\netlify-plugin-handler\integration-test\netlify.toml

> Context
  production

> Loading plugins
   - ../@1.0.0 from netlify.toml

┌─────────────────────────────────┐
│ 1. onPostBuild command from ../ │
└─────────────────────────────────┘

┌─────────────────────────────┐
│ Plugin "../" internal error │
└─────────────────────────────┘

  Error message
  Error: Could not resolve D:a
  etlify-plugin-handler
  etlify-plugin-handlerintegration-testedge-handlersexample module. Please install this locally

  Plugin details
  Package:        ../
  Version:        1.0.0

  Error location
  In "onPostBuild" event in "../" from netlify.toml
      at Object.onwarn (D:\a\netlify-plugin-handler\netlify-plugin-handler\src\index.js:18:335)
      at Object.onwarn (D:\a\netlify-plugin-handler\netlify-plugin-handler\node_modules\rollup\dist\shared\rollup.js:19023:20)
      at ModuleLoader.handleResolveId (D:\a\netlify-plugin-handler\netlify-plugin-handler\node_modules\rollup\dist\shared\rollup.js:17904:26)
      at async Promise.all (index 0)
      at async ModuleLoader.fetchStaticDependencies (D:\a\netlify-plugin-handler\netlify-plugin-handler\node_modules\rollup\dist\shared\rollup.js:17892:34)
      at async Promise.all (index 0)
      at async ModuleLoader.fetchModule (D:\a\netlify-plugin-handler\netlify-plugin-handler\node_modules\rollup\dist\shared\rollup.js:17869:9)
      at async Promise.all (index 0)

  Error properties
  {
    watchFiles: [
      'C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\handlers-mEve5D\\__netlifyMain.ts'
    ]
  }

  Resolved config
  build:
    base: 'D:\a\netlify-plugin-handler\netlify-plugin-handler\integration-test'
    ignore: 'false'
  plugins:
    - inputs: {}
      origin: config
      package: ../
  redirects:
    - edge_function: hello-world
      force: true
      from: /
      status: 200
```

This is unclear whether this is a problem with the source code or the test code, and requires additional investigation.
This fails in Netlify Build tests too, which is not using the same test code, so I am assuming this is probably source code related.

Note: we need Windows support due to Windows users running `netlify build` on the CLI.

### PR DESCRIPTION
**Pull request by ehmicky**
Fixes #36.

On Windows, `path.resolve()` (and even `path.posix.resolve()`) produces backslashes `\` instead of forward slashes `/`. However, ES modules require the use of forward slashes.

This results Edge handlers bundling crashing on Windows. This is only relevant for Netlify CLI users since our buildbot is always using Linux.

This PR fixes it by using [`unixify`](https://github.com/jonschlinkert/unixify). This library has not been maintained in 4 years, which is not great. However, its logic is very small and there are no pending bugs nor PRs. Most importantly, I cannot find any better library for this purpose (please chime in if you know of a better one).

### CODE REVIEW

**Comment by ehmicky** [comment]
Update: this is working locally, but not in CI. Putting the PR back in draft mode.

**Comment by ehmicky** [comment]
Fixed!

The `unixify` library did not work because it removed the drive letter, which does not work when the temporary directory is in a different drive than the build (which is the case inside GitHub actions). I replaced it with only replacing `\` with `/`.

The CI tests are now passing :tada:

File: src/index.js [hunk 1]
```diff
@@ -48,6 +49,17 @@ async function assemble(EDGE_HANDLERS_SRC) {
   return { handlers, mainFile };
 }
 
+// ES modules requires forward slashes
+function unixify(filePath) {
```
Comment (shortdiv) [inline src/index.js:53]: Nifty!

**Review by shortdiv — APPROVED** [review]
